apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicibeckend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicibeckend
  template:
    metadata:
      labels:
        app: medicibeckend
    spec:
      containers:
        - name: app
          image: thembaembot/medicibeckend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/medici_DB?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
